package Form.Customer;

import Class.CustomerCredit;
import Class.UserCustomer;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class Customer_TransactionHistory extends javax.swing.JFrame {

    private CustomerDashboard customerDashboard;
    private UserCustomer usercustomer;
    private CustomerCredit customerCredit;
    private String username;
    private int userID;
    private String customerID;

    public Customer_TransactionHistory(String username, int userID) {
        usercustomer = new UserCustomer();
        customerCredit = new CustomerCredit();
        initComponents();
        this.username = username;
        this.userID = userID;
        customerID = String.valueOf(userID);
        displayTransactionHistory(customerCredit.getTransactionHistoryData(customerID, "All", "All"));
        JTableHeader tableHeader1 = table_TransactionHistory.getTableHeader();
        Font headerFont1 = new Font("Georgia", Font.BOLD, 14);
        tableHeader1.setFont(headerFont1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl_TransactionHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_TransactionHistory = new javax.swing.JTable();
        lbl_TransactionType = new javax.swing.JLabel();
        cmbBox_TransactionType = new javax.swing.JComboBox<>();
        lbl_TransactionDateTime = new javax.swing.JLabel();
        cmbBox_TransactionDateTime = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1014, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));

        lbl_TransactionHistory.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lbl_TransactionHistory.setText("Transaction History:");

        table_TransactionHistory.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        table_TransactionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TransactionID", "Transaction Amount", "Transaction Time", "Transaction Type", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TransactionHistory.setRowHeight(30);
        table_TransactionHistory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_TransactionHistory);
        if (table_TransactionHistory.getColumnModel().getColumnCount() > 0) {
            table_TransactionHistory.getColumnModel().getColumn(2).setMinWidth(80);
            table_TransactionHistory.getColumnModel().getColumn(2).setPreferredWidth(80);
            table_TransactionHistory.getColumnModel().getColumn(4).setMinWidth(100);
            table_TransactionHistory.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        lbl_TransactionType.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbl_TransactionType.setForeground(new java.awt.Color(102, 102, 102));
        lbl_TransactionType.setText("Transaction Type: ");

        cmbBox_TransactionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Transaction Type", "Debit", "Credit" }));
        cmbBox_TransactionType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBox_TransactionTypeItemStateChanged(evt);
            }
        });

        lbl_TransactionDateTime.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbl_TransactionDateTime.setForeground(new java.awt.Color(102, 102, 102));
        lbl_TransactionDateTime.setText("Transaction Date:");

        cmbBox_TransactionDateTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Daily", "Monthly", "Yearly" }));
        cmbBox_TransactionDateTime.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBox_TransactionDateTimeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TransactionHistory)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TransactionType)
                            .addComponent(lbl_TransactionDateTime))
                        .addGap(63, 63, 63)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbBox_TransactionDateTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBox_TransactionType, 0, 195, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_TransactionHistory)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBox_TransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TransactionType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TransactionDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBox_TransactionDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayTransactionHistory(List<List<String>> transactionHistoryData) {
        DefaultTableModel transactionHistoryModel = (DefaultTableModel) table_TransactionHistory.getModel();
        transactionHistoryModel.setRowCount(0);
        for (List<String> transactionHistory : transactionHistoryData) {
            transactionHistoryModel.addRow(transactionHistory.toArray());
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        customerDashboard = new CustomerDashboard(username, userID);
        customerDashboard.setLocationRelativeTo(null);
        customerDashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cmbBox_TransactionTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBox_TransactionTypeItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            String transactionType = (String) cmbBox_TransactionType.getSelectedItem();
            String transactionDateTime = (String) cmbBox_TransactionDateTime.getSelectedItem();
            if (transactionType.equals("All Transaction Type")) {
                transactionType = "All";
            }
            displayTransactionHistory(customerCredit.getTransactionHistoryData(customerID, transactionType, transactionDateTime));
        }
    }//GEN-LAST:event_cmbBox_TransactionTypeItemStateChanged

    private void cmbBox_TransactionDateTimeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBox_TransactionDateTimeItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            String transactionType = (String) cmbBox_TransactionType.getSelectedItem();
            String transactionDateTime = (String) cmbBox_TransactionDateTime.getSelectedItem();
            if (transactionType.equals("All Transaction Type")) {
                transactionType = "All";
            }
            displayTransactionHistory(customerCredit.getTransactionHistoryData(customerID, transactionType, transactionDateTime));
        }
    }//GEN-LAST:event_cmbBox_TransactionDateTimeItemStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_TransactionHistory("", -1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBox_TransactionDateTime;
    private javax.swing.JComboBox<String> cmbBox_TransactionType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_TransactionDateTime;
    private javax.swing.JLabel lbl_TransactionHistory;
    private javax.swing.JLabel lbl_TransactionType;
    private javax.swing.JPanel panel;
    private javax.swing.JTable table_TransactionHistory;
    // End of variables declaration//GEN-END:variables
}
