/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.Admin;

import Form.Login.LoginForm;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

/**
 *
 * @author desmondcwf
 */
public class AdminDashboard extends javax.swing.JFrame {

    private String username;

    public AdminDashboard(String username) {
        initComponents();
        this.username = username;
        lbl_Welcome.setText("Welcome back, " + username);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lbl_LoggedIn.setText("Logged in time: " + dtf.format(now));

        //Create User Button
        btn_CreateUser.setOpaque(true);
        btn_CreateUser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Admin_CreateUser createuser = new Admin_CreateUser();
                createuser.setDefaultCloseOperation(AdminDashboard.DISPOSE_ON_CLOSE);
                createuser.setVisible(true);
                createuser.pack();
                createuser.setLocationRelativeTo(null);
            }
        });
        //Manage User Button
        btn_ManageUser.setOpaque(true);
        btn_ManageUser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Admin_ManageUser manageuser = new Admin_ManageUser();
                manageuser.setDefaultCloseOperation(AdminDashboard.DISPOSE_ON_CLOSE);
                manageuser.setVisible(true);
                manageuser.pack();
                manageuser.setLocationRelativeTo(null);
            }
        });
        //Topup Credit Button 
        btn_Topup.setOpaque(true);
        btn_Topup.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Admin_TopUp topup = new Admin_TopUp();
                topup.setDefaultCloseOperation(AdminDashboard.DISPOSE_ON_CLOSE);
                topup.setVisible(true);
                topup.pack();
                topup.setLocationRelativeTo(null);
            }
        });
        //Generate Transaction Receipt Button
        btn_Generate.setOpaque(true);
        btn_Generate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Admin_GenerateReceipt generate = new Admin_GenerateReceipt();
                generate.setDefaultCloseOperation(AdminDashboard.DISPOSE_ON_CLOSE);
                generate.setVisible(true);
                generate.pack();
                generate.setLocationRelativeTo(null);
            }
        });
        //Logout Button
        btn_Logout.setOpaque(true);
        btn_Logout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                LoginForm login = new LoginForm();
                login.setVisible(true);
                login.pack();
                login.setLocationRelativeTo(null);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_Welcome = new javax.swing.JLabel();
        lbl_LoggedIn = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        btn_CreateUser = new javax.swing.JButton();
        btn_Topup = new javax.swing.JButton();
        btn_ManageUser = new javax.swing.JButton();
        btn_Generate = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel1.setLayout(null);

        Top.setBackground(new java.awt.Color(153, 255, 255));
        Top.setPreferredSize(new java.awt.Dimension(500, 200));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/profile_picture.png"))); // NOI18N

        lbl_Welcome.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lbl_Welcome.setText("abcd");
        lbl_Welcome.setToolTipText("");

        lbl_LoggedIn.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lbl_LoggedIn.setText("ffff");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addComponent(lbl_Logo)
                .addGap(176, 176, 176))
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lbl_Welcome))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbl_LoggedIn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addComponent(lbl_Logo)
                .addGap(12, 12, 12)
                .addComponent(lbl_Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_LoggedIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Top);
        Top.setBounds(0, 0, 500, 200);

        Bottom.setBackground(new java.awt.Color(51, 51, 51));
        Bottom.setPreferredSize(new java.awt.Dimension(500, 500));

        btn_CreateUser.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btn_CreateUser.setText("Create User");
        btn_CreateUser.setBorder(new javax.swing.border.MatteBorder(null));
        btn_CreateUser.setBorderPainted(false);
        btn_CreateUser.setFocusPainted(false);

        btn_Topup.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btn_Topup.setText("Top-up Credit");
        btn_Topup.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Topup.setBorderPainted(false);
        btn_Topup.setFocusPainted(false);

        btn_ManageUser.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btn_ManageUser.setText("Manage User");
        btn_ManageUser.setBorder(new javax.swing.border.MatteBorder(null));
        btn_ManageUser.setBorderPainted(false);
        btn_ManageUser.setFocusPainted(false);

        btn_Generate.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btn_Generate.setText("Generate Receipt");
        btn_Generate.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Generate.setBorderPainted(false);
        btn_Generate.setFocusPainted(false);

        btn_Logout.setBackground(new java.awt.Color(255, 102, 102));
        btn_Logout.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btn_Logout.setText("Logout");
        btn_Logout.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Logout.setBorderPainted(false);
        btn_Logout.setFocusPainted(false);

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Topup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_CreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_ManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_Topup, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_Generate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel1.add(Bottom);
        Bottom.setBounds(0, 200, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btn_CreateUser;
    private javax.swing.JButton btn_Generate;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_ManageUser;
    private javax.swing.JButton btn_Topup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_LoggedIn;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Welcome;
    // End of variables declaration//GEN-END:variables
}
